payment.api.key=${API_KEY}
spring.datasource.url=${URL_POSTGRES}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations